In [13]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

/Users/Yuyang/anaconda/lib/python3.5/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)

In [7]:
url = 'http://olympics.cbc.ca/medals/'
html = requests.get(url).content
soup = BeautifulSoup(html,'lxml')

In [22]:
tr = soup.find_all('tr',{'class':'or-ses-list or-js-sch-active'})
rank = []
country = []
gold = []
silver = []
bronze = []
total = []
for tr_i in tr:
    span = tr_i.find('span',{'class':'orp-rk'})
    rank.append(span.contents[0])
    
    span = tr_i.find('span',{'class':'or-team-n'})
    country.append(span['title'])
    
    td = tr_i.find('td',{'class':'or-md or-gold'})
    gold.append(td.contents[0])

    td = tr_i.find('td',{'class':'or-md or-silver'})
    silver.append(td.contents[0])
    
    td = tr_i.find('td',{'class':'or-md or-bronze'})
    bronze.append(td.contents[0])
    
    td = tr_i.find('td',{'class':'or-md or-total or-l'})
    total.append(td.contents[0])

In [39]:
result = pd.DataFrame({'rank':rank,'country':country,'gold':gold,
                       'silver':silver,'bronze':bronze,'total':total},index=rank)
result = result[['country','gold','silver','bronze','total']]

In [41]:
result

                         country gold silver bronze total
1                  United States   46     37     38   121
2                          China   26     18     26    70
3                  Great Britain   27     23     17    67
4                         Russia   19     18     19    56
5                        Germany   17     10     15    42
6                         France   10     18     14    42
7                          Japan   12      8     21    41
8                      Australia    8     11     10    29
9                          Italy    8     12      8    28
11                   South Korea    9      3      9    21
12                   Netherlands    8      7      4    19
13                        Brazil    7      6      6    19
14                   New Zealand    4      9      5    18
15                    Azerbaijan    1      7     10    18
16                         Spain    7      4      6    17
17                    Kazakhstan    3      5      9    17
18                       Hungary    8      3      4    15
19                       Denmark    2      6      7    15
20                         Kenya    6      6      1    13
21                    Uzbekistan    4      2      7    13
22                       Jamaica    6      3      2    11
23                          Cuba    5      2      4    11
24                        Sweden    2      6      3    11
25                       Ukraine    2      5      4    11
26                        Poland    2      3      6    11
27                       Croatia    5      3      2    10
28                  South Africa    2      6      2    10
29                Czech Republic    1      2      7    10
30                       Belarus    1      4      4     9
31                      Colombia    3      2      3     8
..                           ...  ...    ...    ...   ...
57                       Vietnam    1      1      0     2
59                       Bahamas    1      0      1     2
59                 Côte d'Ivoire    1      0      1     2
59   Independent Olympic Athlete    1      0      1     2
62                       Algeria    0      2      0     2
62                       Ireland    0      2      0     2
64                         India    0      1      1     2
64                      Mongolia    0      1      1     2
66                        Israel    0      0      2     2
67                          Fiji    1      0      0     1
67                        Jordan    1      0      0     1
67                        Kosovo    1      0      0     1
67                   Puerto Rico    1      0      0     1
67                     Singapore    1      0      0     1
67                    Tajikistan    1      0      0     1
73                       Burundi    0      1      0     1
73                       Grenada    0      1      0     1
73                         Niger    0      1      0     1
73                   Philippines    0      1      0     1
73                         Qatar    0      1      0     1
78                       Austria    0      0      1     1
78            Dominican Republic    0      0      1     1
78                       Estonia    0      0      1     1
78                       Finland    0      0      1     1
78                       Morocco    0      0      1     1
78                       Moldova    0      0      1     1
78                       Nigeria    0      0      1     1
78                      Portugal    0      0      1     1
78           Trinidad and Tobago    0      0      1     1
78          United Arab Emirates    0      0      1     1

[86 rows x 5 columns]